const COUNTRIES_AND_CITIES = [
  { country: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'] },
  { country: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'] },
  { country: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'] },
  { country: 'American Samoa', cities: ['Pago Pago', 'Tafuna', 'Leone', 'Faleniu'] },
  { country: 'Andorra', cities: ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria'] },
  { country: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Lubango', 'Cabinda'] },
  { country: 'Anguilla', cities: ['The Valley', 'Blowing Point', 'Sandy Ground'] },
  { country: 'Antarctica', cities: ['McMurdo Station', 'Palmer Station', 'Amundsen-Scott'] },
  { country: 'Antigua and Barbuda', cities: ['St. John\'s', 'All Saints', 'Liberta', 'Potters Village'] },
  { country: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'] },
  { country: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat'] },
  { country: 'Aruba', cities: ['Oranjestad', 'San Nicolas', 'Noord', 'Santa Cruz'] },
  { country: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra'] },
  { country: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'] },
  { country: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'] },
  { country: 'Bahamas', cities: ['Nassau', 'Freeport', 'West End', 'Coopers Town'] },
  { country: 'Bahrain', cities: ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'] },
  { country: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'] },
  { country: 'Barbados', cities: ['Bridgetown', 'Speightstown', 'Oistins', 'Holetown'] },
  { country: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'] },
  { country: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège'] },
  { country: 'Belize', cities: ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk Town'] },
  { country: 'Benin', cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou'] },
  { country: 'Bermuda', cities: ['Hamilton', 'St. George\'s', 'Somerset Village'] },
  { country: 'Bhutan', cities: ['Thimphu', 'Phuntsholing', 'Paro', 'Gelephu'] },
  { country: 'Bolivia', cities: ['Santa Cruz de la Sierra', 'El Alto', 'La Paz', 'Cochabamba', 'Sucre'] },
  { country: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'] },
  { country: 'Botswana', cities: ['Gaborone', 'Francistown', 'Molepolole', 'Maun'] },
  { country: 'Bouvet Island', cities: [] },
  { country: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza'] },
  { country: 'British Indian Ocean Territory', cities: ['Diego Garcia'] },
  { country: 'Brunei Darussalam', cities: ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'] },
  { country: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'] },
  { country: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'] },
  { country: 'Burundi', cities: ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi'] },
  { country: 'Cabo Verde', cities: ['Praia', 'Mindelo', 'Espargos', 'Assomada'] },
  { country: 'Cambodia', cities: ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville'] },
  { country: 'Cameroon', cities: ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam'] },
  { country: 'Canada', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa'] },
  { country: 'Cayman Islands', cities: ['George Town', 'West Bay', 'Bodden Town'] },
  { country: 'Central African Republic', cities: ['Bangui', 'Bimbo', 'Berbérati', 'Carnot'] },
  { country: 'Chad', cities: ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché'] },
  { country: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'] },
  { country: 'China', cities: ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu'] },
  { country: 'Christmas Island', cities: ['Flying Fish Cove', 'Poon Saan'] },
  { country: 'Cocos (Keeling) Islands', cities: ['West Island', 'Home Island'] },
  { country: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'] },
  { country: 'Comoros', cities: ['Moroni', 'Mutsamudu', 'Fomboni'] },
  { country: 'Congo', cities: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi'] },
  { country: 'Democratic Republic of the Congo', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'] },
  { country: 'Cook Islands', cities: ['Avarua', 'Amuri', 'Omoka'] },
  { country: 'Costa Rica', cities: ['San José', 'Alajuela', 'Cartago', 'Heredia'] },
  { country: 'Côte d\'Ivoire', cities: ['Abidjan', 'Bouaké', 'Yamoussoukro', 'Daloa'] },
  { country: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'] },
  { country: 'Cuba', cities: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín'] },
  { country: 'Curaçao', cities: ['Willemstad', 'Sint Michiel', 'Barber'] },
  { country: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'] },
  { country: 'Czechia', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec'] },
  { country: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { country: 'Djibouti', cities: ['Djibouti City', 'Ali Sabieh', 'Dikhil'] },
  { country: 'Dominica', cities: ['Roseau', 'Portsmouth', 'Marigot'] },
  { country: 'Dominican Republic', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís'] },
  { country: 'Ecuador', cities: ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo'] },
  { country: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said'] },
  { country: 'El Salvador', cities: ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel'] },
  { country: 'Equatorial Guinea', cities: ['Malabo', 'Bata', 'Ebebiyin'] },
  { country: 'Eritrea', cities: ['Asmara', 'Keren', 'Massawa', 'Assab'] },
  { country: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'] },
  { country: 'Eswatini', cities: ['Mbabane', 'Manzini', 'Big Bend'] },
  { country: 'Ethiopia', cities: ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Gondar'] },
  { country: 'Falkland Islands (Malvinas)', cities: ['Stanley'] },
  { country: 'Faroe Islands', cities: ['Tórshavn', 'Klaksvík'] },
  { country: 'Fiji', cities: ['Suva', 'Lautoka', 'Nadi', 'Labasa'] },
  { country: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'] },
  { country: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'] },
  { country: 'French Guiana', cities: ['Cayenne', 'Matoury', 'Saint-Laurent-du-Maroni'] },
  { country: 'French Polynesia', cities: ['Papeete', 'Faa\'a', 'Punaauia'] },
  { country: 'French Southern Territories', cities: ['Port-aux-Français'] },
  { country: 'Gabon', cities: ['Libreville', 'Port-Gentil', 'Franceville'] },
  { country: 'Gambia', cities: ['Banjul', 'Serekunda', 'Brikama', 'Bakau'] },
  { country: 'Georgia', cities: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'] },
  { country: 'Germany', cities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne'] },
  { country: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale', 'Takoradi'] },
  { country: 'Gibraltar', cities: ['Gibraltar'] },
  { country: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'] },
  { country: 'Greenland', cities: ['Nuuk', 'Sisimiut', 'Ilulissat'] },
  { country: 'Grenada', cities: ['St. George\'s', 'Gouyave', 'Grenville'] },
  { country: 'Guadeloupe', cities: ['Les Abymes', 'Baie-Mahault', 'Le Gosier'] },
  { country: 'Guam', cities: ['Dededo', 'Yigo', 'Tamuning', 'Hagåtña'] },
  { country: 'Guatemala', cities: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'] },
  { country: 'Guernsey', cities: ['Saint Peter Port'] },
  { country: 'Guinea', cities: ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia'] },
  { country: 'Guinea-Bissau', cities: ['Bissau', 'Bafatá', 'Gabú'] },
  { country: 'Guyana', cities: ['Georgetown', 'Linden', 'New Amsterdam'] },
  { country: 'Haiti', cities: ['Port-au-Prince', 'Carrefour', 'Delmas', 'Cap-Haïtien'] },
  { country: 'Heard Island and McDonald Islands', cities: [] },
  { country: 'Holy See', cities: ['Vatican City'] },
  { country: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'] },
  { country: 'Hong Kong', cities: ['Kowloon', 'Victoria City', 'Sha Tin', 'Tuen Mun'] },
  { country: 'Hungary', cities: ['Budapest', 'Debrecen', 'Szeged', 'Miskolc'] },
  { country: 'Iceland', cities: ['Reykjavík', 'Kópavogur', 'Hafnarfjörður'] },
  { country: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata'] },
  { country: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang'] },
  { country: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz'] },
  { country: 'Iraq', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Najaf'] },
  { country: 'Ireland', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'] },
  { country: 'Isle of Man', cities: ['Douglas', 'Ramsey', 'Peel'] },
  { country: 'Israel', cities: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion'] },
  { country: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo'] },
  { country: 'Jamaica', cities: ['Kingston', 'Portmore', 'Spanish Town', 'Montego Bay'] },
  { country: 'Japan', cities: ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo'] },
  { country: 'Jersey', cities: ['Saint Helier'] },
  { country: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid', 'Russeifa'] },
  { country: 'Kazakhstan', cities: ['Almaty', 'Astana', 'Shymkent', 'Karaganda'] },
  { country: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'] },
  { country: 'Kiribati', cities: ['Tarawa', 'Betio', 'Bikenibeu'] },
  { country: 'North Korea', cities: ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo'] },
  { country: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon'] },
  { country: 'Kuwait', cities: ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Salmiya'] },
  { country: 'Kyrgyzstan', cities: ['Bishkek', 'Osh', 'Jalal-Abad'] },
  { country: 'Laos', cities: ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang'] },
  { country: 'Latvia', cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'] },
  { country: 'Lebanon', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'] },
  { country: 'Lesotho', cities: ['Maseru', 'Teyateyaneng', 'Mafeteng'] },
  { country: 'Liberia', cities: ['Monrovia', 'Gbarnga', 'Buchanan', 'Ganta'] },
  { country: 'Libya', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'] },
  { country: 'Liechtenstein', cities: ['Vaduz', 'Schaan', 'Triesen'] },
  { country: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai'] },
  { country: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Dudelange'] },
  { country: 'Macao', cities: ['Macau'] },
  { country: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'] },
  { country: 'Malawi', cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'] },
  { country: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Johor Bahru'] },
  { country: 'Maldives', cities: ['Malé', 'Addu City', 'Fuvahmulah'] },
  { country: 'Mali', cities: ['Bamako', 'Sikasso', 'Kalabancoro', 'Koutiala'] },
  { country: 'Malta', cities: ['Valletta', 'Birkirkara', 'Mosta', 'St. Paul\'s Bay'] },
  { country: 'Marshall Islands', cities: ['Majuro', 'Ebeye'] },
  { country: 'Martinique', cities: ['Fort-de-France', 'Le Lamentin', 'Le Robert'] },
  { country: 'Mauritania', cities: ['Nouakchott', 'Nouadhibou', 'Kiffa'] },
  { country: 'Mauritius', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'] },
  { country: 'Mayotte', cities: ['Mamoudzou', 'Koungou'] },
  { country: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'] },
  { country: 'Micronesia', cities: ['Palikir', 'Weno', 'Colonia'] },
  { country: 'Moldova', cities: ['Chisinau', 'Balti', 'Tiraspol', 'Bender'] },
  { country: 'Monaco', cities: ['Monaco', 'Monte Carlo', 'La Condamine'] },
  { country: 'Mongolia', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan'] },
  { country: 'Montenegro', cities: ['Podgorica', 'Nikšić', 'Herceg Novi'] },
  { country: 'Montserrat', cities: ['Brades', 'Plymouth'] },
  { country: 'Morocco', cities: ['Casablanca', 'Rabat', 'Fes', 'Tangier', 'Marrakesh'] },
  { country: 'Mozambique', cities: ['Maputo', 'Matola', 'Beira', 'Nampula'] },
  { country: 'Myanmar', cities: ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine'] },
  { country: 'Namibia', cities: ['Windhoek', 'Rundu', 'Walvis Bay'] },
  { country: 'Nauru', cities: ['Yaren', 'Denigomodu', 'Meneng'] },
  { country: 'Nepal', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar'] },
  { country: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'] },
  { country: 'New Caledonia', cities: ['Nouméa', 'Dumbéa', 'Le Mont-Dore'] },
  { country: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton'] },
  { country: 'Nicaragua', cities: ['Managua', 'León', 'Masaya', 'Matagalpa'] },
  { country: 'Niger', cities: ['Niamey', 'Maradi', 'Zinder', 'Tahoua'] },
  { country: 'Nigeria', cities: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt'] },
  { country: 'Niue', cities: ['Alofi'] },
  { country: 'Norfolk Island', cities: ['Kingston', 'Burnt Pine'] },
  { country: 'North Macedonia', cities: ['Skopje', 'Bitola', 'Kumanovo', 'Prilep'] },
  { country: 'Northern Mariana Islands', cities: ['Saipan', 'Tinian', 'Rota'] },
  { country: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'] },
  { country: 'Oman', cities: ['Muscat', 'Seeb', 'Salalah', 'Bawshar'] },
  { country: 'Pakistan', cities: ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi'] },
  { country: 'Palau', cities: ['Ngerulmud', 'Koror', 'Airai'] },
  { country: 'Palestine', cities: ['Gaza City', 'East Jerusalem', 'Hebron', 'Nablus', 'Ramallah'] },
  { country: 'Panama', cities: ['Panama City', 'San Miguelito', 'Tocumen', 'David'] },
  { country: 'Papua New Guinea', cities: ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen'] },
  { country: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'Luque', 'San Lorenzo'] },
  { country: 'Peru', cities: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Cusco'] },
  { country: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City'] },
  { country: 'Pitcairn', cities: ['Adamstown'] },
  { country: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'] },
  { country: 'Portugal', cities: ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'] },
  { country: 'Puerto Rico', cities: ['San Juan', 'Bayamón', 'Carolina', 'Ponce'] },
  { country: 'Qatar', cities: ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah'] },
  { country: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași'] },
  { country: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan'] },
  { country: 'Rwanda', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'] },
  { country: 'Réunion', cities: ['Saint-Denis', 'Saint-Paul', 'Saint-Pierre'] },
  { country: 'Saint Barthélemy', cities: ['Gustavia'] },
  { country: 'Saint Helena, Ascension and Tristan da Cunha', cities: ['Jamestown', 'Georgetown', 'Edinburgh of the Seven Seas'] },
  { country: 'Saint Kitts and Nevis', cities: ['Basseterre', 'Charlestown'] },
  { country: 'Saint Lucia', cities: ['Castries', 'Gros Islet', 'Vieux Fort'] },
  { country: 'Saint Martin (French part)', cities: ['Marigot'] },
  { country: 'Saint Pierre and Miquelon', cities: ['Saint-Pierre', 'Miquelon-Langlade'] },
  { country: 'Saint Vincent and the Grenadines', cities: ['Kingstown', 'Georgetown'] },
  { country: 'Samoa', cities: ['Apia', 'Vaitele', 'Faleasiu'] },
  { country: 'San Marino', cities: ['San Marino', 'Serravalle', 'Borgo Maggiore'] },
  { country: 'Sao Tome and Principe', cities: ['São Tomé', 'Trindade'] },
  { country: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'] },
  { country: 'Senegal', cities: ['Dakar', 'Touba', 'Thiès', 'Rufisque'] },
  { country: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac'] },
  { country: 'Seychelles', cities: ['Victoria', 'Anse Etoile'] },
  { country: 'Sierra Leone', cities: ['Freetown', 'Bo', 'Kenema', 'Makeni'] },
  { country: 'Singapore', cities: ['Singapore'] },
  { country: 'Sint Maarten (Dutch part)', cities: ['Philipsburg', 'Lower Prince\'s Quarter'] },
  { country: 'Slovakia', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina'] },
  { country: 'Slovenia', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'] },
  { country: 'Solomon Islands', cities: ['Honiara', 'Gizo', 'Auki'] },
  { country: 'Somalia', cities: ['Mogadishu', 'Hargeisa', 'Bosaso', 'Galkayo'] },
  { country: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Gqeberha'] },
  { country: 'South Georgia and the South Sandwich Islands', cities: ['King Edward Point', 'Grytviken'] },
  { country: 'South Sudan', cities: ['Juba', 'Malakal', 'Wau', 'Yambio'] },
  { country: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza'] },
  { country: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna'] },
  { country: 'Sudan', cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala'] },
  { country: 'Suriname', cities: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'] },
  { country: 'Svalbard and Jan Mayen', cities: ['Longyearbyen', 'Barentsburg'] },
  { country: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'] },
  { country: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne'] },
  { country: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia'] },
  { country: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan'] },
  { country: 'Tajikistan', cities: ['Dushanbe', 'Khujand', 'Bokhtar', 'Kulob'] },
  { country: 'Tanzania', cities: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Zanzibar City'] },
  { country: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Nonthaburi'] },
  { country: 'Timor-Leste', cities: ['Dili', 'Baucau', 'Maliana'] },
  { country: 'Togo', cities: ['Lomé', 'Sokodé', 'Kara', 'Kpalimé'] },
  { country: 'Tokelau', cities: ['Atafu', 'Nukunonu', 'Fakaofo'] },
  { country: 'Tonga', cities: ['Nuku\'alofa', 'Neiafu', 'Haveluloto'] },
  { country: 'Trinidad and Tobago', cities: ['Port of Spain', 'San Fernando', 'Chaguanas', 'Arima'] },
  { country: 'Tunisia', cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan'] },
  { country: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana'] },
  { country: 'Turkmenistan', cities: ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary'] },
  { country: 'Turks and Caicos Islands', cities: ['Cockburn Town', 'Providenciales'] },
  { country: 'Tuvalu', cities: ['Funafuti'] },
  { country: 'Uganda', cities: ['Kampala', 'Nansana', 'Kira', 'Mbarara'] },
  { country: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Lviv'] },
  { country: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain'] },
  { country: 'United Kingdom', cities: ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Edinburgh', 'Liverpool'] },
  { country: 'United States Minor Outlying Islands', cities: [] },
  { country: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'] },
  { country: 'Uruguay', cities: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú'] },
  { country: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Namangan', 'Andijan'] },
  { country: 'Vanuatu', cities: ['Port Vila', 'Luganville'] },
  { country: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto'] },
  { country: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho'] },
  { country: 'Virgin Islands (British)', cities: ['Road Town', 'Spanish Town'] },
  { country: 'Virgin Islands (U.S.)', cities: ['Charlotte Amalie', 'Christiansted', 'Frederiksted'] },
  { country: 'Wallis and Futuna', cities: ['Mata-Utu', 'Alele', 'Falaleu'] },
  { country: 'Western Sahara', cities: ['Laayoune', 'Dakhla', 'Smara'] },
  { country: 'Yemen', cities: ['Sana\'a', 'Aden', 'Taiz', 'Hodeidah'] },
  { country: 'Zambia', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe'] },
  { country: 'Zimbabwe', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare'] },
  { country: 'Åland Islands', cities: ['Mariehamn'] }
];

module.exports = { COUNTRIES_AND_CITIES };